id = "vercel-theme"
name = "Vercel Theme"
version = "0.0.0"
schema_version = 1
authors = ["Lumirelle <lumirelle@outlook.com>"]
description = "▲ Vercel light and dark theme, like in Vercel's docs."
repository = "https://github.com/lumirelle/zed-vercel-theme"
